---
- hosts: all
  become: yes
  tasks:
    - name: deploy apache1
      community.docker.docker_container:
        name: apache1
        image: httpd:alpine
        ports:
          - 8000:80
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/vagrant/resources/web-1/web-1.html:/usr/local/apache2/htdocs/index.html
        restart_policy: always


- hosts: all
  become: yes
  tasks:
    - name: deploy apache2
      community.docker.docker_container:
        name: apache2
        image: httpd:alpine
        ports:
          - 8001:80
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/vagrant/resources/web-2/web-2.html:/usr/local/apache2/htdocs/index.html
        restart_policy: always



